kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: build
  image: docker:latest
  commands:
  - apk add --update --no-cache bash build-base go curl rsync python3 python2 git
  - make images
  settings:
    repo: ellisvalentiner/ambassador
    tags: linux-amd64-${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: ellisvalentiner/ambassador:${DRONE_BRANCH}
    template: ellisvalentiner/ambassador:OS-ARCH-${DRONE_BRANCH}
    platforms:
      - linux/arm64

depends_on:
- linux-arm64
